defmodule ScrypathEcommerceWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :scrypath_ecommerce

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_scrypath_ecommerce_key",
    signing_salt: "1I+1zvgH",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :scrypath_ecommerce,
    gzip: not code_reloading?,
    only: ScrypathEcommerceWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :scrypath_ecommerce
  end

  # Runtime-gated so the e2e browser lane can disable the sandbox via config/runtime.exs
  # (SCRYPATH_E2E_NO_SANDBOX=1) without tripping Application.compile_env validation at boot.
  # The plug is always compiled in; it no-ops when :sandbox is false/nil.
  plug :maybe_sql_sandbox

  @doc false
  def maybe_sql_sandbox(conn, _opts) do
    case Application.get_env(:scrypath_ecommerce, :sandbox) do
      nil -> conn
      false -> conn
      sandbox -> Phoenix.Ecto.SQL.Sandbox.call(conn, Phoenix.Ecto.SQL.Sandbox.init(sandbox: sandbox))
    end
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ScrypathEcommerceWeb.Router
end
