import Config

# Configure your database
config :scrypath_ops, ScrypathOps.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: String.to_integer(System.get_env("PGPORT") || "5432"),
  database: System.get_env("SCRYPATH_OPS_DATABASE_NAME") || "scrypath_ops_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :scrypath_ops, ScrypathOpsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "tA4gkT1b+1xvLi2wfsuRhAnfswO0Q6WHBzre4AbFYz5esSr1JCjH3sxLPeSDVXNk",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:scrypath_ops, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:scrypath_ops, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :scrypath_ops, ScrypathOpsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/scrypath_ops_web/router\.ex$",
      ~r"lib/scrypath_ops_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :scrypath_ops, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :scrypath_ops, :validate_opsui_auth_on_start, false
config :scrypath_ops, standalone: true

config :scrypath_ops,
  backend: Scrypath.Meilisearch,
  meilisearch_url: System.get_env("SCRYPATH_OPS_MEILISEARCH_URL") || "http://localhost:7700"

# OPSUI schema allowlist: set `SCRYPATH_OPS_SCHEMAS=MyApp.Blog.Post` at runtime,
# or assign `config :scrypath_ops, :schema_allowlist, [MyApp.Blog.Post]` here.
# Do not use reflection to populate the list.

# Writable playbook workspace for local dev (repo-local `tmp/playbooks`).
playbook_dev_root = Path.expand("tmp/playbooks", Path.join(__DIR__, ".."))
File.mkdir_p!(playbook_dev_root)

config :scrypath_ops, :playbook_workspace_dir, playbook_dev_root
